### ISSUE TITLE
Did twitch fix this?

### ISSUE THREAD

**Issue by igrutinovicl** [Sam6734/TwitchViewbot#3]
Because when I start the bot I can hear the stream if I turn on audio but the views don't go up.

**Comment by Sam6734** [comment]
no, recopy the code I made a change to show the stream instead of audio only. Also if you're not using residential or social media proxies twitch will block the proxy after 1-2 minutes based on reputation.

**Comment by igrutinovicl** [comment]
Okay, thanks for the quick response.
